#!/usr/bin/env bash
set -e

cd "$(dirname "$0")"/..

export NODE_PATH=/usr/lib/nodejs:static

INDEX_JS=frontend_tests/node_tests/index.js
NODEJS=$(which nodejs || which node)
if [ "$1" = "cover" ]; then
  # Run a coverage test with Istanbul.
  istanbul cover "$INDEX_JS"

elif [ "$1" = "-h" -o "$1" = "--help" ]; then
  echo "Usage:
`basename $0`                             - to run all tests
`basename $0` file_name.js                - to run tests from file_name.js
`basename $0` file_name1.js file_name2.js - to run tests from file_name1.js and file_name2.js
"
  exit 0

else
  # Normal testing, no coverage analysis.
  # Run the index.js test runner, which runs all the other tests.
  "$NODEJS" --stack-trace-limit=100 "$INDEX_JS" $@
fi
